### ISSUE TITLE
no rnn_probability_file

### ISSUE THREAD

**Issue by fivehills** [langcomp/lm_1b#2]
There are two problems in running LSTM script:
 1. Everything has been set according to the instruction (there is only one thing different from the instruction; a similar corpus with the same format as Dundee has been used), and then implement rnn_corpus.py. There is no error shown; however, it can not produce this file rnn_probability_file. Exactly there is no extra files produced.

 2. When implementing the script process_experiment.py, I've got the error:
  File "process_experiment.py", line 5, in <module>
    import create_logprob_corpus_vectors
ImportError: No module named create_logprob_corpus_vectors
   Actually there is no file called create_logprob_corpus_vectors in the folder.
  So how to solve them? 

   Thanks!

**Comment by angoodkind** [comment]
1. You need to manually create a file that is assigned to the variable `rnn_probability_file`.
2. Sorry, you should comment this out. I will make a note on the README, but this is not necessary for calculating these surprisals.
